# Setup an Postquest server locally in an Docker Container

# version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: smartrecon_db
    restart: always
    environment:
      POSTGRES_DB: smartrecon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: